### ISSUE TITLE
Please ignore the kid here @G9-Dev

### ISSUE THREAD

**Issue by thatdolphinguy** [G9-Dev/BSoD4U#10]
Just block him from accessing this repo. And honestly every other repo you have. @G9-Dev-real is just like 2 years old, no, A atom still.

**Comment by Darik2121** [comment]
No he's not 2 liar

**Comment by Nestor5Cat** [comment]
Close your mouth, Who the heck are you >:(

**Comment by Nestor5Cat** [comment]
Just block him from accessing this repo. And honestly every other repo you have. @thatdolphinguy is just like 14 years old, no, a s@#*m. A at?m still.

**Comment by Nestor5Cat** [comment]
@thatdolphinguy i removed your Stupid Profile Picture when using Adblock. Just stop chatting here

**Comment by Darik2121** [comment]
you know what? this is a github repo not a discrod chat

**Comment by Nestor5Cat** [comment]
nickel naily needle fries coiny teardrop

**Comment by thatdolphinguy** [comment]
> @thatdolphinguy i removed your Stupid Profile Picture when using Adblock. Just stop typing here

imagine using Adblock to block a PFP

**Comment by G9-Dev** [comment]
> > @thatdolphinguy i removed your Stupid Profile Picture when using Adblock. Just stop typing here
> 
> imagine using Adblock to block a PFP

Imagine 🤣

**Comment by G9-Dev** [comment]
Anyways @G9-Dev-real i sold your ip for 20$ thanks
Prepare yourself
