### ISSUE TITLE
not so fast

### ISSUE THREAD

**Issue by Darik2121** [G9-Dev/BSoD4U#11]
$sudo unsell @G9-Dev-real ip address

**Comment by Nestor5Cat** [comment]
I dont care about this, this malware is so annoying! I dont wanna type in here anymore!!! >:(

**Comment by Darik2121** [comment]
i already heard that

**Comment by Nestor5Cat** [comment]
just see wha i created in seconds ago...

**Comment by Nestor5Cat** [comment]
THATS ENOUGH @G9-Dev, ONE MORE WORD AND I HACK/HECK YOU!

**Comment by G9-Dev** [comment]
shut the fuck up looser
