### ISSUE TITLE
You spamming

### ISSUE THREAD

**Issue by G9-dev-real** [G9-Dev/BSoD4U#4]
i had enough one more word and i steal your password

**Comment by G9-Dev** [comment]
blah blah

**Comment by G9-Dev** [comment]
https://progaming.monster/3QJHHO.png
This obviously you

**Comment by G9-Dev** [comment]
Ok. Now listen : please delete this account now. Please.

**Comment by G9-Dev** [comment]
Now delete your account.
Bad things are gonna happen otherwise if you don't delete it in 24 hours.
Your IP ends with 166.

**Comment by G9-dev-real** [comment]
I dont

**Comment by G9-dev-real** [comment]
It's just GitHub what could go wrong lol

**Comment by G9-dev-real** [comment]
@G9-Dev I'm reporting you

**Comment by G9-dev-real** [comment]
G9-Dev please delete your account pls

**Comment by G9-dev-real** [comment]
Its so nice to close this issue

**Comment by G9-Dev** [comment]
Okay, you wanted it. Gotta sell your IP adress now :)

**Comment by G9-dev-real** [comment]
No no don't do that

**Comment by G9-dev-real** [comment]
You don't know my IP address lol

**Comment by G9-dev-real** [comment]
So I'll sell yours

**Comment by G9-dev-real** [comment]
> Okay, you wanted it. Gotta sell your IP adress now :)

Your profile is 💩

**Comment by G9-dev-real** [comment]
My IP is 237.199.251.126 😂

**Comment by G9-Dev** [comment]
I obviously will and i will until you delete this account
